package com.demo.common.model;

import com.demo.common.model.base.BaseTblBookversion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TblBookversion extends BaseTblBookversion<TblBookversion> {
	
}
