package com.demo.common.model;

import com.demo.common.model.base.BaseTblDayRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TblDayRecord extends BaseTblDayRecord<TblDayRecord> {
	
}
