package com.demo.common.model;

import com.demo.common.model.base.BaseTblGrade;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TblGrade extends BaseTblGrade<TblGrade> {
	
}
