package com.demo.common.model;

import com.demo.common.model.base.BaseTblRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TblRecord extends BaseTblRecord<TblRecord> {
	
}
