package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTblBook<M extends BaseTblBook<M>> extends Model<M> implements IBean {

	public void setBid(java.lang.Integer bid) {
		set("bid", bid);
	}
	
	public java.lang.Integer getBid() {
		return getInt("bid");
	}

	public void setBvid(java.lang.Integer bvid) {
		set("bvid", bvid);
	}
	
	public java.lang.Integer getBvid() {
		return getInt("bvid");
	}

	public void setBname(java.lang.String bname) {
		set("bname", bname);
	}
	
	public java.lang.String getBname() {
		return getStr("bname");
	}

	public void setGid(java.lang.Integer gid) {
		set("gid", gid);
	}
	
	public java.lang.Integer getGid() {
		return getInt("gid");
	}

	public void setBimgPath(java.lang.String bimgPath) {
		set("bimgPath", bimgPath);
	}
	
	public java.lang.String getBimgPath() {
		return getStr("bimgPath");
	}

	public void setBunitAccount(java.lang.Integer bunitAccount) {
		set("bunitAccount", bunitAccount);
	}
	
	public java.lang.Integer getBunitAccount() {
		return getInt("bunitAccount");
	}

}
