package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTblUser<M extends BaseTblUser<M>> extends Model<M> implements IBean {

	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	public void setUname(java.lang.String uname) {
		set("uname", uname);
	}
	
	public java.lang.String getUname() {
		return getStr("uname");
	}

	public void setUcity(java.lang.String ucity) {
		set("ucity", ucity);
	}
	
	public java.lang.String getUcity() {
		return getStr("ucity");
	}

	public void setUheadPath(java.lang.String uheadPath) {
		set("uheadPath", uheadPath);
	}
	
	public java.lang.String getUheadPath() {
		return getStr("uheadPath");
	}

	public void setUphone(java.lang.String uphone) {
		set("uphone", uphone);
	}
	
	public java.lang.String getUphone() {
		return getStr("uphone");
	}

	public void setUpassword(java.lang.String upassword) {
		set("upassword", upassword);
	}
	
	public java.lang.String getUpassword() {
		return getStr("upassword");
	}

	public void setUbirth(java.util.Date ubirth) {
		set("ubirth", ubirth);
	}
	
	public java.util.Date getUbirth() {
		return get("ubirth");
	}

	public void setVip(java.lang.Integer vip) {
		set("vip", vip);
	}
	
	public java.lang.Integer getVip() {
		return getInt("vip");
	}

}
