package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTblDayRecord<M extends BaseTblDayRecord<M>> extends Model<M> implements IBean {

	public void setDrid(java.lang.Integer drid) {
		set("drid", drid);
	}
	
	public java.lang.Integer getDrid() {
		return getInt("drid");
	}

	public void setError(java.lang.Integer error) {
		set("error", error);
	}
	
	public java.lang.Integer getError() {
		return getInt("error");
	}

	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	public void setRight(java.lang.Integer right) {
		set("right", right);
	}
	
	public java.lang.Integer getRight() {
		return getInt("right");
	}

	public void setSum(java.lang.Integer sum) {
		set("sum", sum);
	}
	
	public java.lang.Integer getSum() {
		return getInt("sum");
	}

	public void setDate(java.util.Date date) {
		set("date", date);
	}
	
	public java.util.Date getDate() {
		return get("date");
	}

	public void setAcc(java.lang.Double acc) {
		set("acc", acc);
	}
	
	public java.lang.Double getAcc() {
		return getDouble("acc");
	}

}
