package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTblGrade<M extends BaseTblGrade<M>> extends Model<M> implements IBean {

	public void setGit(java.lang.Integer git) {
		set("git", git);
	}
	
	public java.lang.Integer getGit() {
		return getInt("git");
	}

	public void setGname(java.lang.String gname) {
		set("gname", gname);
	}
	
	public java.lang.String getGname() {
		return getStr("gname");
	}

	public void setGtype(java.lang.Integer gtype) {
		set("gtype", gtype);
	}
	
	public java.lang.Integer getGtype() {
		return getInt("gtype");
	}

}
