package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTblWord<M extends BaseTblWord<M>> extends Model<M> implements IBean {

	public void setWid(java.lang.Integer wid) {
		set("wid", wid);
	}
	
	public java.lang.Integer getWid() {
		return getInt("wid");
	}

	public void setWenglish(java.lang.String wenglish) {
		set("wenglish", wenglish);
	}
	
	public java.lang.String getWenglish() {
		return getStr("wenglish");
	}

	public void setWchinese(java.lang.String wchinese) {
		set("wchinese", wchinese);
	}
	
	public java.lang.String getWchinese() {
		return getStr("wchinese");
	}

	public void setUnId(java.lang.Integer unId) {
		set("unId", unId);
	}
	
	public java.lang.Integer getUnId() {
		return getInt("unId");
	}

	public void setBid(java.lang.Integer bid) {
		set("bid", bid);
	}
	
	public java.lang.Integer getBid() {
		return getInt("bid");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

}
