package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTblUnit<M extends BaseTblUnit<M>> extends Model<M> implements IBean {

	public void setUnid(java.lang.Integer unid) {
		set("unid", unid);
	}
	
	public java.lang.Integer getUnid() {
		return getInt("unid");
	}

	public void setUnName(java.lang.String unName) {
		set("unName", unName);
	}
	
	public java.lang.String getUnName() {
		return getStr("unName");
	}

	public void setBid(java.lang.Integer bid) {
		set("bid", bid);
	}
	
	public java.lang.Integer getBid() {
		return getInt("bid");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

}
