package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTblBookversion<M extends BaseTblBookversion<M>> extends Model<M> implements IBean {

	public void setBvId(java.lang.Integer bvId) {
		set("bvId", bvId);
	}
	
	public java.lang.Integer getBvId() {
		return getInt("bvId");
	}

	public void setBvName(java.lang.String bvName) {
		set("bvName", bvName);
	}
	
	public java.lang.String getBvName() {
		return getStr("bvName");
	}

	public void setBvType(java.lang.Integer bvType) {
		set("bvType", bvType);
	}
	
	public java.lang.Integer getBvType() {
		return getInt("bvType");
	}

	public void setBvPubTime(java.util.Date bvPubTime) {
		set("bvPubTime", bvPubTime);
	}
	
	public java.util.Date getBvPubTime() {
		return get("bvPubTime");
	}

}
